# Generated by Django 4.0.6 on 2022-07-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=180, verbose_name='рост'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=112, verbose_name='вес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, verbose_name='возраст'),
        ),
    ]
